apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "maven-hello-world.fullname" . }}
  labels:
    {{- include "maven-hello-world.labels" . | nindent 4 }}
data:
  application.properties: |
    server.port=8080
    server.shutdown=graceful
    spring.application.name=maven-hello-world
    logging.level.root=INFO
    logging.level.com.myapp=DEBUG
    management.endpoints.web.exposure.include=health,info,metrics
    management.endpoint.health.show-details=always
